source 'https://github.com/sora0077/PodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'iTunesMusicKitDemo' do
  pod 'iTunesMusicKit', :path => '../'
  pod 'RxSwift', '~> 2.0.0-beta'
  pod 'RxCocoa', '~> 2.0.0-beta'
  pod 'RxBlocking', '~> 2.0.0-beta'
end

target 'iTunesMusicKitDemoTests' do

end

target 'iTunesMusicKitDemoUITests' do

end
